/* Build script: hip_main.csv -> js/stars-hip.js (+ snaps named stars in data.js) */
'use strict';
const fs = require('fs');
const path = 'C:/Users/press/OneDrive/Projects/DSH_TESTS/planetarium/';

/* ---------- 1. parse CSV ---------- */
console.log('reading CSV...');
const csv = fs.readFileSync(path + '_build/hip_main.csv', 'utf8');
const lines = csv.split('\n');
const header = lines[0].split(',');
const col = name => header.indexOf(name);
const I_RA = col('RA_Deg'), I_DEC = col('Dec_Deg'), I_V = col('Vmag'),
      I_BV = col('BV_Color'), I_VMAG2 = col('Hip_Mag');
console.log('columns:', { I_RA, I_DEC, I_V, I_BV, I_VMAG2 });
const stars = [];
let skipped = 0;
for (let i = 1; i < lines.length; i++) {
  const line = lines[i];
  if (!line || line.charCodeAt(0) === 13) continue;
  const c = line.split(',');
  const ra = parseFloat(c[I_RA]);
  const dec = parseFloat(c[I_DEC]);
  let v = parseFloat(c[I_V]);
  if (!isFinite(v)) v = parseFloat(c[I_VMAG2]); // fall back to Hip_Mag
  if (!isFinite(ra) || !isFinite(dec) || !isFinite(v)) { skipped++; continue; }
  if (v > 11.5) { skipped++; continue; }
  let bv = parseFloat(c[I_BV]);
  if (!isFinite(bv)) bv = 0.9;
  stars.push({ ra, dec, v, bv });
}
console.log(`catalog stars: ${stars.length} (skipped ${skipped})`);

/* ---------- 2. named stars from data.js ---------- */
const dataPath = path + 'js/data.js';
let dataJs = fs.readFileSync(dataPath, 'utf8');
const namedRe = /\[\s*'([^']+)',\s*([\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*(-?[\d.]+),\s*([\d.]+|null)\s*\]/g;
const named = [];
let m;
while ((m = namedRe.exec(dataJs)) !== null) {
  named.push({ name: m[1], ra: +m[2], dec: +m[3], full: m[0], index: m.index, pos: m.index + m[0].length });
}
console.log(`named stars in data.js: ${named.length}`);

const D2R = Math.PI / 180;
function unit(ra, dec) {
  const d = dec * D2R, a = ra * D2R;
  const cd = Math.cos(d);
  return [cd * Math.cos(a), Math.sin(d), -cd * Math.sin(a)];
}
const catalogVecs = stars.map(s => unit(s.ra, s.dec));

let snapped = 0, unmatched = [];
const excluded = new Set();
for (const n of named) {
  const nv = unit(n.ra, n.dec);
  let best = -1, bestDot = 0;
  for (let i = 0; i < stars.length; i++) {
    const c = catalogVecs[i];
    const dot = nv[0]*c[0] + nv[1]*c[1] + nv[2]*c[2];
    if (dot > bestDot) { bestDot = dot; best = i; }
  }
  const angDeg = Math.acos(Math.min(1, bestDot)) / D2R;
  if (best >= 0 && angDeg < 1.0) {
    const s = stars[best];
    // rewrite the named star entry with the exact catalog position
    const old = `[...`.length ? '' : '';
    const entry = namedRe; // (keep original indices)
    const re = new RegExp(`\\[\\s*'${n.name.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')}',\\s*${esc(n.ra)},\\s*${esc(n.dec)}`, 'g');
    dataJs = dataJs.replace(re, `['${n.name}', ${s.ra.toFixed(5)}, ${s.dec.toFixed(5)}`);
    excluded.add(best);
    snapped++;
    if (angDeg > 0.05) console.log(`  snap ${n.name}: offset ${angDeg.toFixed(3)} deg`);
  } else {
    unmatched.push(n.name);
  }
}
function esc(x) { return String(x).replace(/\./g, '\\.').replace(/-/g, '-'); }
console.log(`snapped: ${snapped}, unmatched: ${unmatched.length ? unmatched.join(', ') : 'none'}`);
fs.writeFileSync(dataPath, dataJs);

/* ---------- 3. emit binary star buffer ---------- */
const out = stars.filter((_, i) => !excluded.has(i));
const N = out.length;
const buf = new ArrayBuffer(N * 16);
const f32 = new Float32Array(buf);
for (let i = 0; i < N; i++) {
  f32[i*4]   = out[i].ra;
  f32[i*4+1] = out[i].dec;
  f32[i*4+2] = out[i].v;
  f32[i*4+3] = out[i].bv;
}
const b64 = Buffer.from(buf).toString('base64');
console.log(`emitting ${N} stars, ${b64.length} bytes of base64`);
const js = `/* AUTO-GENERATED by _build/convert.js — do not edit.
 * Hipparcos main catalog (ESA SP-1200, public domain), 118,218 stars.
 * Each record: [RA deg, Dec deg, V mag, B-V] as Float32.
 * The 83 stars also listed in data.js are excluded (drawn separately,
 * with labels); their data.js positions were snapped to this catalog.
 */
'use strict';
window.P = window.P || {};
P.starsHip = {
  count: ${N},
  b64: "${b64}"
};
`;
fs.writeFileSync(path + 'js/stars-hip.js', js);
console.log('done -> js/stars-hip.js');
