// One-shot build: world city gazetteer for the journey feature (From/To
// addresses like "London", "Tokyo", "Lagos").
// Source: GeoNames `cities5000` (CC-BY) — every settlement with population
// >= 5000.  Run:  node _build/fetch-cities.mjs
// Output: js/cities.js  —  P.cities = [[name, iso, lat, lon, pop, country], ...]
import { writeFileSync } from 'node:fs';

import { fileURLToPath } from 'node:url';

const URLS = [
  'https://download.geonames.org/export/dump/cities5000.zip',
];
const binPath = fileURLToPath(new URL('../_cities5000.zip', import.meta.url));

let buf = null;
for (const u of URLS) {
  try {
    const res = await fetch(u);
    if (!res.ok) { console.error(u, 'HTTP', res.status); continue; }
    buf = Buffer.from(await res.arrayBuffer());
    console.log('downloaded', u, buf.length, 'bytes');
    break;
  } catch (e) { console.error(u, e.message); }
}
if (!buf) { console.error('download failed'); process.exit(1); }
writeFileSync(binPath, buf);

/* unzip via the platform tar (Windows bsdtar reads zip archives) */
import { execFileSync } from 'node:child_process';
import { readFileSync, existsSync } from 'node:fs';
const dirPath = fileURLToPath(new URL('.', import.meta.url));
const txtPath = fileURLToPath(new URL('cities5000.txt', import.meta.url));
if (!existsSync(txtPath)) {
  execFileSync('tar', ['-xf', binPath, '-C', dirPath]);
}
const text = readFileSync(txtPath, 'utf8');

/* geonames columns (this dump): 0 id,1 name,2 asciiname,3 alt,4 lat,5 lon,
   6 fclass,7 fcode,8 country,9 admin1,10-12 admin2-4,13 ?,14 population,
   15 elevation,16 ?,17 timezone,18 date */
const MIN_POP = 50000;   /* towns only — keeps the gazetteer small */
const lines = text.split('\n');
const seen = new Map();
for (const line of lines) {
  if (!line) continue;
  const c = line.split('\t');
  if (c.length < 15) continue;
  const name = (c[2] || c[1] || '').trim();          // asciiname preferred
  const lat = parseFloat(c[4]), lon = parseFloat(c[5]);
  const cc = c[8] || '';
  const pop = +(c[14] || 0);
  if (!name || !isFinite(lat) || !isFinite(lon) || pop < MIN_POP) continue;
  const key = name.toLowerCase() + '|' + cc;
  const prev = seen.get(key);
  if (!prev || pop > prev[4]) seen.set(key, [name, cc, +lat.toFixed(4), +lon.toFixed(4), pop, c[9] || '']);
}
const rows = [...seen.values()].sort((a, b) => b[4] - a[4]);
const js = `/* AUTO-GENERATED by _build/fetch-cities.mjs — do not edit.
 * World city gazetteer for the journey feature's From/To addresses.
 * Source: GeoNames \`cities5000\` (CC-BY) — settlements with population >= 5000.
 * P.cities = [[name, iso, lat, lon, population, admin1], ...] sorted by pop. */
'use strict';
window.P = window.P || {};
P.cities = ${JSON.stringify(rows)};
P.citiesCount = ${rows.length};
`;
writeFileSync(new URL('../js/cities.js', import.meta.url), js);
console.log(`wrote js/cities.js: ${rows.length} cities, ${(js.length / 1024).toFixed(0)} KB`);
